### ISSUE TITLE
error while running the script 

### ISSUE THREAD

**Issue by sakshisharma1413** [lschmiddey/fastpages_#14]
NameError                                 Traceback (most recent call last)
[<ipython-input-19-e0d2ddddde39>](https://localhost:8080/#) in <module>----> 1 D_in = data_set.x.shape[1]      2 H = 50      3 H2 = 12      4 model = Autoencoder(D_in, H, H2).to(device)      5 optimizer = optim.Adam(model.parameters(), lr=1e-3)
NameError: name 'data_set' is not defined.

I am doing in google colab . 

also 

ValueError                                Traceback (most recent call last)
[<ipython-input-30-c118f16641b9>](https://localhost:8080/#) in <module>
      1 import array
      2 scaler = trainloader.dataset.standardizer
----> 3 recon_row = scaler.inverse_transform(recon_batch[0].cpu().numpy())
      4 real_row = scaler.inverse_transform(testloader.dataset.x[0].cpu().numpy()

**Comment by lschmiddey** [comment]
which notebook are you referring to? There are still some blogposts on the old version, I recommend trying to follow this tutorial here: https://lschmiddey.github.io/fastpages_/2022/02/19/DataAugmentation_vs_SMOTE.html

**Comment by sakshisharma1413** [comment]
Hi , 
can we produce the data with string in this repo?

**Comment by lschmiddey** [comment]
This is not how the library works anymore, this version is outdated and deprecated. Please try the tutorial in the comment from above :)

**Comment by lschmiddey** [comment]
with the new version some things did change, but there is also the notebook for that included
