### ISSUE TITLE
Statistical correlation between fake and real data

### ISSUE THREAD

**Issue by Laish93** [lschmiddey/fastpages_#16]
Hey! your repository was awesome and I have done quite a similar job to that in which I had some imbalanced dataset and augmented the data because of that. Now I have augmented fake data and real data in histograms. Both histograms actually look really nice and well fit each other.  However, do you know how I can calculate the statistical relationship between those two histograms (fake data histogram and real data histogram)?

Thank you. 
Cheers!

**Comment by lschmiddey** [comment]
if you want to check whether two distributions are similar, you should use the Kolmogorov-Smirnov test like here: https://stats.stackexchange.com/questions/211743/how-to-determine-the-similarity-between-histograms

**Comment by lschmiddey** [comment]
closed
