### ISSUE TITLE
Errors encountered when running -tabular-data-variational-autoencoder.ipynb

### ISSUE THREAD

**Issue by sparshgarg23** [lschmiddey/fastpages_#8]
Hi,I executed your colab and ran into the following errors
1.When executing df = pd.DataFrame(np.stack((recon_row, real_row)), columns = cols)
the following error is encountered

ValueError: Must pass 2-d input. shape=(2, 1, 14)
2.On executing  the following block
scaler = trainloader.dataset.standardizer
recon_row = scaler.inverse_transform(recon_batch[0].cpu().numpy())
real_row = scaler.inverse_transform(testloader.dataset.x[0].cpu().numpy())

It seems recon_batch[0] should be placed in square brackets not doing so raises the following error
Expected 2d array instead got 1d array

When executing the cells under generate fake data
On executing the following block
df_fake = pd.DataFrame(fake_data, columns = cols)
df_fake['Wine'] = np.round(df_fake['Wine']).astype(int)
df_fake['Wine'] = np.where(df_fake['Wine']<1, 1, df_fake['Wine'])
df_fake.head(10)
keyerror Wine is raised

Same error is raised  under compare variables grouped by Wine
df_base.groupby('Wine').mean()
keyerror Wine 

Would you be able to help me in fixing them,

**Comment by sparshgarg23** [comment]
Hi,I was able to resolve the key error issue but the rest of them still remain.
Also you might want to replace data_set with trainloader.dataset

**Comment by lschmiddey** [comment]
hey sparshgarg23,
you're right in that regard, I try to fix that on the weekend. However, I would recommend using the refactored approach: https://github.com/lschmiddey/deep_tabular_augmentation/blob/main/deep_data_augmentation.ipynb

**Comment by sparshgarg23** [comment]
ok thanks.
